name: 'CiviCRM'
description: 'Install CiviCRM and CiviCRM Entity.'
type: 'Administration' 
install:
  - package_manager
  # Contrib.
  - civicrm
  - civicrmtheme
config:
  strict: false
  actions:
    civicrmtheme.settings:
      simple_config_update:
        admin_theme: gin
    package_manager.settings:
      simple_config_update:
        executables:
          composer: null
          rsync: null
        additional_trusted_composer_plugins:
          - civicrm/civicrm-asset-plugin
          - civicrm/composer-compile-plugin
          - civicrm/composer-downloads-plugin
        include_unknown_files_in_project_root: true
   # Assign CiviCRM permissions to user roles.        
    user.role.anonymous:
      grantPermissions:
        - 'access all custom data'
        - 'access CiviMail subscribe/unsubscribe pages'
        - 'make online contributions'
        - 'profile create'
        - 'profile edit'
        - 'profile view'
        - 'register for events'
        - 'view event info'
        - 'view event participants'
    user.role.authenticated:
      grantPermissions:
        - 'access all custom data'
        - 'access CiviMail subscribe/unsubscribe pages'
        - 'access uploaded files'
        - 'edit my contact'
        - 'make online contributions'
        - 'profile create'
        - 'profile edit'
        - 'profile view'
        - 'register for events'
        - 'view event info'
        - 'view event participants'
    user.role.membership:
      createIfNotExists:
        label: 'Membership Coordinator'
      grantPermissions:
        # Group 1
        - 'access CiviCRM'
        - 'access CiviMail'
        - 'delete in CiviMail'
        - 'view public CiviMail content'
        # Group 2
        - 'access civicrm group role setting'      
        - 'access CiviReport'
        - 'access Report Criteria'
        - 'administer Reports'
        - 'edit all contacts'
        - 'edit groups'
        - 'edit message templates'
        - 'save Report Criteria'
        - 'view all contacts'
        # Group 3 - assigned to membership & site_admin.
        - 'access CiviContribute'
        - 'access CiviEvent'
        - 'access CiviMember'
        - 'access Contact Dashboard'
        - 'access deleted contacts'
        - 'add contact notes'
        - 'add contacts'
        - 'administer CiviCRM'
        - 'administer CiviCRM data'
        - 'administer dedupe rules'
        - 'administer Tagsets'
        - 'delete contacts'
        - 'delete in CiviContribute'
        - 'delete in CiviEvent'
        - 'delete in CiviMember'
        - 'edit all events'
        - 'edit contributions'
        - 'edit event participants'
        - 'edit inbound email basic information'
        - 'edit inbound email basic information and content'
        - 'edit memberships'
        - 'edit system workflow message templates'
        - 'edit user-driven message templates'
        - 'manage event profiles'
        - 'manage tags'
        - 'merge duplicate contacts'
        - 'send SMS'
        - 'view all activities'
        - 'view all notes'
    user.role.site_admin:
      createIfNotExists:
        label: 'Site administrator'
      grantPermissions:
        # Group 1
        - 'access CiviCRM'
        - 'access CiviMail'
        - 'delete in CiviMail'
        - 'view public CiviMail content'      
        # Group 2
        - 'access civicrm group role setting'
        - 'access CiviReport'
        - 'access Report Criteria'
        - 'administer Reports'
        - 'edit all contacts'
        - 'edit groups'
        - 'edit message templates'
        - 'save Report Criteria'
        - 'view all contacts'
        # Group 3
        - 'access CiviContribute'
        - 'access CiviEvent'
        - 'access CiviMember'
        - 'access Contact Dashboard'
        - 'access deleted contacts'
        - 'add contact notes'
        - 'add contacts'
        - 'administer CiviCRM'
        - 'administer CiviCRM data'
        - 'administer dedupe rules'
        - 'administer Tagsets'
        - 'delete contacts'
        - 'delete in CiviContribute'
        - 'delete in CiviEvent'
        - 'delete in CiviMember'
        - 'edit all events'
        - 'edit contributions'
        - 'edit event participants'
        - 'edit inbound email basic information'
        - 'edit inbound email basic information and content'
        - 'edit memberships'
        - 'edit system workflow message templates'
        - 'edit user-driven message templates'
        - 'manage event profiles'
        - 'manage tags'
        - 'merge duplicate contacts'
        - 'send SMS'
        - 'view all activities'
        - 'view all notes'
        # Group 4 - assigned to site_admin only.
        - 'administer CiviCRM system'
