executables:
  composer: null
  rsync: null
additional_trusted_composer_plugins:
  - civicrm/civicrm-asset-plugin
  - civicrm/composer-compile-plugin
  - civicrm/composer-downloads-plugin
include_unknown_files_in_project_root: true